### ISSUE TITLE
Problem with python and MAP++

### ISSUE THREAD

**Issue by salicto** [old-NWTC/MAP#1]
Hello,

I am not familiar with python language. I'm trying to get Map++ to work on python but lo and behold I had trouble getting it to work standalone. I attach with this message the two Python files necessary for the operation of MAP++. I get a name type error "ModelData_Type' is not defined". This error comes from the mapsys.py file. I don't quite understand because I haven't touched this file. If I understood correctly it is just used to load the DLL library. Any help will be welcome...

Thanks in advance,
[PythonFile.zip](https://github.com/old-NWTC/MAP/files/8115982/PythonFile.zip)

**Comment by jjonkman** [comment]
Dear @salicto,

I haven't reviewed your files, but I'm curious why you posted here and not on the OpenFAST github site: https://github.com/OpenFAST/openfast.  Do you still have the problem when using MAP++ within OpenFAST?  If so, I suggest you post your question there instead of here.

Best regards,

**Comment by salicto** [comment]
Dear Jonkman,

**Comment by salicto** [comment]
Dear Jonkman,

I thought that the questions corresponding to the problems with the MAP++ code should be solved in the forum related to the module.

I thought I was doing well, I will change the forum

Best regards,

**Comment by jjonkman** [comment]
Dear @salicto,

This site is an old archive of MAP++.  All active development of MAP++ and other OpenFAST modules takes place on the OpenFAST github site: https://github.com/OpenFAST/openfast.

Best regards,
